# Generated by Django 4.0.1 on 2022-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_symbol', models.CharField(max_length=10)),
                ('one_step', models.CharField(max_length=10)),
                ('two_step', models.CharField(max_length=10)),
                ('final_step', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profitability', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
