# Generated by Django 4.0.1 on 2022-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_bundle_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinancePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('base_asset', models.CharField(max_length=10, unique=True)),
                ('second_asset', models.CharField(max_length=10, unique=True)),
                ('last_price', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
