# Generated by Django 4.0.1 on 2022-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_binancepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancepair',
            name='last_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
