# Generated by Django 4.0.1 on 2022-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_binancepair_last_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancepair',
            name='base_asset',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='binancepair',
            name='second_asset',
            field=models.CharField(max_length=10),
        ),
    ]
