# Generated by Django 4.0.1 on 2022-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_binancepair_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='binancepair',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
