# Generated by Django 4.0.1 on 2022-06-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_binancepair_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceBudle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final', to='trading.binancepair')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start', to='trading.binancepair')),
                ('step_next', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_next', to='trading.binancepair')),
            ],
        ),
    ]
