# Generated by Django 4.0.1 on 2022-06-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_binancebudle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binancebudle',
            old_name='start',
            new_name='first_pair',
        ),
        migrations.RenameField(
            model_name='binancebudle',
            old_name='step_next',
            new_name='second_pair',
        ),
        migrations.RenameField(
            model_name='binancebudle',
            old_name='final',
            new_name='third_pair',
        ),
        migrations.AddField(
            model_name='binancebudle',
            name='start_stop_symbol',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
