# Generated by Django 4.0.1 on 2022-06-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_rename_start_binancebudle_first_pair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancebudle',
            name='first_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_pair', to='trading.binancepair'),
        ),
        migrations.AlterField(
            model_name='binancebudle',
            name='second_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_pair', to='trading.binancepair'),
        ),
        migrations.AlterField(
            model_name='binancebudle',
            name='third_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='third_pair', to='trading.binancepair'),
        ),
    ]
