# Generated by Django 4.0.1 on 2022-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_alter_binancebudle_first_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binancebudle',
            name='first_step_symbol',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='binancebudle',
            name='second_step_symbol',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
