# Generated by Django 4.0.1 on 2022-04-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funnel_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funnel_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.IntegerField(default=0)),
                ('text_message', models.TextField()),
                ('json_data', models.JSONField()),
                ('answer_to', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('funnel_name', models.CharField(max_length=250)),
                ('delay_before', models.IntegerField(default=0)),
                ('delay_after', models.IntegerField(default=0)),
                ('message_photo', models.ImageField(upload_to='telemontr/static/dialog_images')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnels.funnel')),
            ],
        ),
    ]
