# Generated by Django 4.0.1 on 2022-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funnel_message',
            name='funnel_name',
        ),
        migrations.AlterField(
            model_name='funnel_message',
            name='message_photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
