# Generated by Django 4.0.1 on 2022-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0002_remove_funnel_message_funnel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnel_message',
            name='message_photo',
            field=models.ImageField(upload_to='funnels_images/'),
        ),
    ]
