# Generated by Django 4.0.1 on 2022-02-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True)),
                ('session_file', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register_time', models.IntegerField(default=0)),
                ('proxy', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('first_name', models.CharField(default='-', max_length=250)),
                ('last_name', models.CharField(default='-', max_length=250)),
                ('last_check_time', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('password', models.BooleanField(default=False)),
                ('password_str', models.CharField(default='-', max_length=250)),
                ('avatar', models.CharField(default='-', max_length=250)),
                ('username', models.CharField(default='-', max_length=250)),
                ('work', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
                ('action', models.CharField(default='-', max_length=255)),
                ('online', models.BooleanField(default=False)),
                ('invite_restricted', models.BooleanField(default=False)),
                ('message_restricted', models.BooleanField(default=False)),
            ],
        ),
    ]
