# Generated by Django 4.0.1 on 2022-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram_account',
            name='password_str',
        ),
        migrations.AlterField(
            model_name='telegram_account',
            name='last_check_time',
            field=models.DateTimeField(),
        ),
    ]
