# Generated by Django 4.0.1 on 2022-02-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_account',
            name='password',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
