# Generated by Django 4.0.1 on 2022-02-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_telegram_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_account',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
