# Generated by Django 4.0.1 on 2022-02-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_telegram_account_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_account',
            name='last_check_time',
            field=models.DateTimeField(null=True),
        ),
    ]
