# Generated by Django 4.0.1 on 2022-02-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_telegram_account_last_check_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_account',
            name='twoFA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telegram_account',
            name='first_name',
            field=models.CharField(default='-', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='telegram_account',
            name='last_name',
            field=models.CharField(default='-', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='telegram_account',
            name='username',
            field=models.CharField(default='-', max_length=250, null=True),
        ),
    ]
