# Generated by Django 4.0.1 on 2022-02-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_telegram_account_twofa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_account',
            name='str_password',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
