# Generated by Django 4.0.1 on 2022-02-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_telegram_account_session_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='host',
            field=models.GenericIPAddressField(),
        ),
    ]
