# Generated by Django 4.0.1 on 2022-02-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_proxy_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
