# Generated by Django 4.0.1 on 2022-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_proxy_port_alter_proxy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='host',
            field=models.CharField(max_length=100),
        ),
    ]
