# Generated by Django 4.0.1 on 2022-02-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_proxy_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='host',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
