# Generated by Django 4.0.1 on 2022-02-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_proxy_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram_account',
            name='proxy',
        ),
    ]
