# Generated by Django 4.0.1 on 2022-02-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_telegram_account_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_account',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.proxy'),
        ),
    ]
