# Generated by Django 4.0.1 on 2022-03-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_telegram_account_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.IntegerField(default=0)),
                ('text_message', models.TextField()),
                ('json_data', models.JSONField()),
                ('answer_to', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('funnel_name', models.CharField(max_length=250)),
                ('delay_before', models.IntegerField(default=0)),
                ('delay_after', models.IntegerField(default=0)),
            ],
        ),
    ]
