# Generated by Django 4.0.1 on 2022-03-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_funnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funnel',
            name='answer_to',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='delay_after',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='delay_before',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='index_id',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='text_message',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='user_id',
        ),
        migrations.CreateModel(
            name='Funnel_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.IntegerField(default=0)),
                ('text_message', models.TextField()),
                ('json_data', models.JSONField()),
                ('answer_to', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('funnel_name', models.CharField(max_length=250)),
                ('delay_before', models.IntegerField(default=0)),
                ('delay_after', models.IntegerField(default=0)),
                ('message_photo', models.ImageField(upload_to='telemontr/static/dialog_images')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.funnel')),
            ],
        ),
    ]
