# Generated by Django 4.0.1 on 2022-03-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_funnel_answer_to_remove_funnel_delay_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnel',
            name='funnel_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
